import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { WalletContextProvider } from "@/context/wallet";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <WalletContextProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar/>
          {children}
          <div className="lg:px-10 pt-12 pb-4 bg-black">
            <Footer/>
          </div>
        </body>
      </WalletContextProvider>
    </html>
  );
}
